### ISSUE TITLE
10.0.2.3 Renown Reputation gains go off-chart (retail)

### ISSUE THREAD

**Issue by layzsmurf** [tvlfrosty/Reputation_Guide#33]
I have Tuskarr Renown level 13 and the addon seems to have a problem calculating higher renown levels / gains. Below is a chat message for a renown gain:
```
[18:47:54] Netting More completed.
[18:48:39] Reputation with Iskaara Tuskarr increased by 2750. (Total: +85450, Left to Renown 15: -78802)
[18:48:39] Reputation with Iskaara Tuskarr increased by 2500. (Total: +87950, Left to Renown 15: -81302)
[18:48:39] Reputation with Iskaara Tuskarr increased by 2500. (Total: +90450, Left to Renown 15: -83802)

```
The value for renown 13 are 1.302 out of 2.500

On login the numbers are fine until I gain a new renown level. It seems that increase is not properly handled.

**Comment by tvlfrosty** [comment]
I will have a look at this tonight, Thought it was fixed, but the Renown system works super weird when hitting a new Renown level.

**Comment by layzsmurf** [comment]
Ok, I think I can supply more useful information.

The bug seems to happen upon renown gain. E.g. 13->14. Somehow the system then prints left to renown 15 - one level higher. This happens quite consistently.  I am not sure how the addon works inside - if you check every X seconds - or If you get an event from Blizzard. Shoehow it seems you get the event twice - or two checks happen somehow.

**Comment by tvlfrosty** [comment]
Hey,
Sorry I wasn't able to update back on this yet, been busy lately.

Those messages / checks are after specific events, of which one is when you gain reputation.
The problem with the new factions is that they have a seperate reputation value, which is obviously Renown, but under the hood they still have a set reputation value, so I am guessing at a certain Renown level it breaks the addon function.

Because at lower Renown levels it seems to work fine atm.

![Wow_WpCD05Gdkm](https://user-images.githubusercontent.com/8556252/208762492-af7c219e-c7ab-4ba2-8061-46bd0793200a.png)
![Wow_mrQyFxkpNY](https://user-images.githubusercontent.com/8556252/208762584-5b924bb6-f53b-40c0-bd89-ac7146fb9e0d.png)
![Wow_PibnR7Tji6](https://user-images.githubusercontent.com/8556252/208762521-5e15e0c1-1953-4418-8adb-c62d57af765e.png)

So I will continue leveling my renown levels to see if a higher renown causes the issue, and hope to have a permanent solution soon!

**Comment by Seriphe** [comment]
With alts it happens immediately. I don't mind reloading, but alts getting a rep boost thanks to your main's renown level has made them a bit more frequent. 
![WoWScrnShot_011023_014939](https://user-images.githubusercontent.com/122347917/211492851-f7ef329a-dd29-4c6b-8042-77fb62f8075b.jpg)

**Comment by tvlfrosty** [comment]
Hey @Seriphe thanks for the further update that it's also causing issues for alts, I hope to be able to work on it again soon.

**Comment by Seriphe** [comment]
@tvlfrosty  Sorry to comment again, but I may have found (part) of the problem. I use altoholic, and it doesn't like my dracthyr for some reason. I finally brought her to the Isles, and she didn't have the above problem. Turned altoholic off on my shaman, and she didn't get it either. Can't test with my main until Tuesday, and I don't know if layzsmurf also uses it, but it looks like there's some odd interaction with altoholic for alts at least.

**Comment by layzsmurf** [comment]
I am using Altoholic.

**Comment by tvlfrosty** [comment]
Hmm interesting, if I see the highest line before it says Renown level 2 was reached that is the line it should only show, it looks like the Reputation Guide print function is fired 3 more times, which only happends during like faction update events.

I will take a look at the connection to Altoholic addon. see if it's calling those events manually... 

Thanks for the updates guys, I really hope to look into this isseue soon, as it's the biggest issue currerntly.

**Comment by Kyrgune** [comment]
It's not an Altoholic issue, I get the same and don't use it.  Just wanted to save you the time if you are planning on looking into it.

**Comment by tvlfrosty** [comment]
> It's not an Altoholic issue, I get the same and don't use it. Just wanted to save you the time if you are planning on looking into it.

Thanks for the update! I plan on playing my Dracthyr character soon to see if I can reproduce the problem with low renown levels, after playing on warrior for a bit, to see if there is a connection between alts even without Altoholic.

This issue is currently on the top of my list for Retail, but with the release of Classic Ulduar/lunar festival + IRL work I haven't had much time to actively play retail, apologies.

**Comment by tvlfrosty** [comment]
Apologies if people are still having this issue, if you are please let me know with what exactly you were doing (which quest/mob you received reputation from), if you have a main that has the renown buff unlocked for an alt, if there was a specific event that gives a reputation gain buff.

I believe the thing that 'can' trigger it for example is a quest that gives more than 2500 renown. As it will trigger the renown update multiple times for 1 quest, But I can't say for sure.

While I do plan to play a little more retail during TWW, also to add the new factions to the addon. I will mainly play Classic Cataclysm.
So if you are missing a certain faction or quest in the addon, please don't hesitate to create an issue, those kind of issues are very quickly fixed luckily, compared to bugs like this that require lots of testing.

So apologies again if this one is still an issue for some, I really hope once I play more again I can find a permanent fix.

For now I will add it to the bulk list #63
