### ISSUE TITLE
10.1 - No UI & /rep not responding

### ISSUE THREAD

**Issue by inthenightsky** [tvlfrosty/Reputation_Guide#41]
Unsure if this addon is still being maintained but it doesn't appear to be working in 10.1, it's completely wiped out my reputation window and when I do /rep nothing appears.

A few snippets of the script errors that occur:

https://gist.github.com/inthenightsky/f779b478a08f3ad8931ba424a1a6dde4
https://gist.github.com/inthenightsky/8b1739070153fcd548109660476a0977
https://gist.github.com/inthenightsky/61aeb47ea56e36107db7fa21a0fafad4

There's 45 errors in total but looking through it all appears to be repetitions of those. Possibly a dupe of #29?

**Comment by tvlfrosty** [comment]
I haven't had much time to fix the retail version of the addon since the 10.0 release, as the UI api broke a lot of the addon and I mainly play Classic WotLK myself, testing takes more time than I have had past months.

I do want to fix the addon eventually, but I apologies for the inconvenience in the meantime.

**Comment by tvlfrosty** [comment]
This shouldn't be a problem anymore with the later releases. If it is please let me know.
