### ISSUE TITLE
Possible fix for 10.1.7 error

### ISSUE THREAD

**Issue by Hyphie24** [tvlfrosty/Reputation_Guide#42]
5x ReputationGuide:RegisterEvent(): ReputationGuide:RegisterEvent(): Attempt to register unknown event "UPDATE_TRADESKILL_RECAST"
[string "=[C]"]: in function `RegisterEvent'
[string "@ReputationGuide/ReputationGuide.lua"]:346: in function `REP_OnEvent'
[string "*ReputationGuide.xml:11_OnEvent"]:1: in function <[string "*ReputationGuide.xml:11_OnEvent"]:1>

Locals:
(*temporary) = ReputationGuide {
 0 = <userdata>
}
(*temporary) = "UPDATE_TRADESKILL_RECAST"

Change line 346 in ReputationGuide.lua from
REP_Main:RegisterEvent("UPDATE_TRADESKILL_RECAST")

to

REP_Main:RegisterEvent("UPDATE_TRADESKILL_CAST_STOPPED")

**Comment by tvlfrosty** [comment]
Thanks for posting the issue + possible sulution!

I am going to do some testing on normal server tomorrow, because I am not even sure that "UPDATE_TRADESKILL_RECAST" is needed for what it's currently used for.

Once I am done with some testing I will push an update to curseforge to at least fix the error for PTR server.

**Comment by tvlfrosty** [comment]
Apologies, didn't realise the 10.1.7 Patch was this close to release, I remove the RegisterEvent completely for 10.1.7 onwards, as it didn't seem to do much. I will keep monitoring things in case it causes any unwanted behaviour...

Update is currently being uploaded to Curseforge, this should fix the error.

Thanks again for reporting the issue!
