### ISSUE TITLE
bad argument #1 to 'lower' (string expected, got nil)

### ISSUE THREAD

**Issue by Quartzfire** [tvlfrosty/Reputation_Guide#49]
Updated recently, and get following LUA on login:

20x ...eputationGuide/Retail_Temp/RetailReputationGuide.lua:1404: bad argument #1 to 'lower' (string expected, got nil)
[string "=[C]"]: in function `lower'
[string "@ReputationGuide/Retail_Temp/RetailReputationGuide.lua"]:1404: in function `REP_AddMob'
[string "@ReputationGuide/content.lua"]:53: in function `REP_InitEnFactionGains'
[string "@ReputationGuide/Retail_Temp/RetailReputationGuide.lua"]:627: in function `Init'
[string "@ReputationGuide/Retail_Temp/RetailReputationGuide.lua"]:423: in function `REP_OnEvent'
[string "*RetailReputationGuide.xml:11_OnEvent"]:1: in function <[string "*RetailReputationGuide.xml:11_OnEvent"]:1>

Locals:
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by tvlfrosty** [comment]
@Quartzfire is there no newer version available atm? The latest version should have replaced the seperate LUA file for retail, could you check if there is a newer version available on Curse or try removing the addon folder and getting a fresh install?

**Comment by Quartzfire** [comment]
> @Quartzfire is there no newer version available atm? The latest version should have replaced the separate LUA file for retail, could you check if there is a newer version available on Curse or try removing the addon folder and getting a fresh install?

Indeed there is. Strange - curseforge wasn't listing it as a new update, but when I went down to the addon it did indeed say "Update". I've updated now and don't see the LUA any more.

Thanks very much, and apologies for any inconvenience.

**Comment by tvlfrosty** [comment]
Glad it's working now, and no need to apologies, I am happy when people report issues because it's difficult to test all wow versions alone when I really only play classic wotlk/cata myself. 

The reason I noticed the version was outdated was because I replaced the "Retail_Temp/RetailReputationGuide.lua" with the same file as all other wow versions in the 2nd version I made that included all wow versions, which makes it alot easier for myself to test the addon in all wow versions.

So happy it's working as expected now, if there is any other issues don't hesitate to report them!
