### ISSUE TITLE
Script running too long

### ISSUE THREAD

**Issue by Peregran** [tvlfrosty/Reputation_Guide#79]
Newest release 1.2.3:

2x ReputationGuide/ReputationGuide.lua:606: script ran too long
[string "@ReputationGuide/ReputationGuide.lua"]:606: in function `Init'
[string "@ReputationGuide/ReputationGuide.lua"]:453: in function `REP_OnEvent'
[string "*ReputationGuide.xml:11_OnEvent"]:1: in function <[string "*ReputationGuide.xml:11_OnEvent"]:1>

Locals:
self = <table> {
 IsClassicPhaseFour = false
 LIMIT_TYPE_Incr = 12
 AfterCata = true
 ShowDragonflightPhaseThree = true
 ShowClassicPhaseFour = true
 AfterClassic = true
 Version = "11.0.0-release"
 ShowClassicSOMPhaseFour = false
 IsDragonflightPhaseOne = false
 IsTheLastTitan = false
 LIMIT_TYPE_Ench = 10
 Tools = <table> {
 }
 IsClassicSOD = false

**Comment by Starlynk1** [comment]
This is a killer for the game, locks up the whole window until that script times out and wow proceeds. Nearly game breaking bug.

**Comment by tvlfrosty** [comment]
I will have a look at it right away

**Comment by Peregran** [comment]
I was just logging into my character and the system hung at the screen after selecting my toon and before the game screen appeared.

**Comment by Starlynk1** [comment]
I was turning in the daily quest for the echoes event

**Comment by tvlfrosty** [comment]
Hmm alright, so the main script that is causing it is only loaded once which should indeed be upon login. But it would affect further reputation turn ins / quests based on how many factions you have unlocked...

I am trying to find a different way to do this at the moment because I really don't want to force people to have all reputation headers expanded to see the reputation values printed...

11.0.0 somehow changed the behaviour of `GetNumFactions()` and it only returns visible factions now.

**Comment by tvlfrosty** [comment]
I reverted some of the changes in the 1.2.4-release that is currently being uploaded to Curseforge, this should fix the long load times that the previous update caused.

But will break the reputation messages again if a faction is not visible in the ReputationFrame due to collapsed headers and the option "Replace original faction gain messages with a more detailed version" is turned on.

I will keep looking for a fix for that specific issue which was mentioned in the #63. But in the meantime hopefully this will affect less people.

And for the people that are affected by the issue where the chat message are not shown, please either turn of the option mentioned above or make sure the faction you are gaining reputation with is visible in the ReputationFrame until I can come up with a better fix for the changes to `C_Reputation.GetNumFactions()`.

**Comment by Starlynk1** [comment]
Very strange that this would be an issue. According to the 11.0.2.56162 API, C_Reputation.GetNumFactions has not been deprecated and is still available to call upon. I'm not an expert of coding, so unfortunately, I can't help with a reason why it failed now.
________________________________

**Comment by tvlfrosty** [comment]
Hey @Starlynk1, it is indeed still available, but before 11.0.0 it was just `GetNumFactions()`, it's now moved to the namespace `C_Reputation.GetNumFactions()`. And with that it seems it's now only returning the visible factions. So if one of the expansion headers is collapsed it no longer returns those 'hidden' factions.

It used to work fine before 11.0.0, so I am assuming those new expansion/faction headers are somehow causing the hidden factions not to be returned with `C_Reputation.GetNumFactions()` which is a massive issue for the addon at the moment.

I personally don't have that many factions unlocked on my retail character so all my headers were expanded and It was showing the reputation values in chat as expected, so I didn't notice the problem during the 11.0.0 patch, untill someone mentioned it after the 11.0.2 patch.
