### ISSUE TITLE
Reputation Change

### ISSUE THREAD

**Issue by Zariah2725** [tvlfrosty/Reputation_Guide#89]
Cataclysm Classic : When gaining reputation, the rep bar does not switch to the reputation that you just gained. It remains on whichever one you had checked to put as experience bar. I have unchecked all reps to make sure there isnt one that is listed as "show as experience bar" to see if that fixed it, and it doesnt. I also made sure that the option to have it switch to the faction of the reputation just gained was checked and it is. It was working fine until the update and then just stopped switching the reps.

**Comment by tvlfrosty** [comment]
I will have a look at it later today, thanks for letting me know!

**Comment by Zariah2725** [comment]
No problem! Thank you for responding. I truly enjoy your addon

**Comment by tvlfrosty** [comment]
Hmm, yea looks like you can no longer set a faction as watched by their faction ID... Not sure why that was removed, but I build in a fix that if for some reason it's available it will use that way, otherwise it will use the old way of using the index of the faction list.

Should be fixed in the 1.3.2-release that is being uploaded to curse, once it's uploaded and approved I will close the issue.

**Comment by tvlfrosty** [comment]
Alright the 1.3.2-release is approved on curse, and the issue should be fixed now, if there is any further issues with the addon please let me know!

**Comment by Zariah2725** [comment]
Thank you so much!! I will let you know if there are any other issues. I appreciate your hard work 


Sent from Yahoo Mail for iPhone


On Wednesday, November 6, 2024, 6:39 PM, tvlfrosty ***@***.***> wrote:




Alright the 1.3.2-release is approved on curse, and the issue should be fixed now, if there is any further issues with the addon please let me know!
